# Site settings
title: .好久不见
description: *这里是Xu_Yang的个人主页*
baseurl: "" 
#change the baseurl to "" if you are using it as your user GitHub Pages
url: "https://xuyang233.github.io"  


# GitHub User settings
username: XuYang
github_username: XuYang233
user_description: 编程初学者
user_title: Grammar Beginner
email: 

# Blog Author settings
author:
  name: XuYang            
  picture:        
  email: 25425035058@qq.com          
  description: I'm just a grammar beginner    
  twitter:
  facebook:
  github: https://github.com/XuYang233/         
  linkedin:
  clustrmap:      


# markdown
markdown: kramdown
  
kramdown:
 footnote_nr: 1
 entity_output: as_char
 # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
 syntax_highlighter: rouge
 syntax_highlighter_opts:
  # Use existing pygments syntax highlighting css
  css_class: 'highlight'
 span:
  line_numbers: false
 block:
  line_numbers: true
  start_line: 1
 
highlighter: rouge
    
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  
permalink: none

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      toc: true
      mathjax: true
      mermaid: false
      highlight: false
      numbering: true
      status: Completed
      protected: false
      commentable: true
      rss: true
      numbering: true


exclude:
 - LICENSE.md
 - README.md
 - "*.cdf"
 - "*.nb"
 - "*.bk"
 - "*.draft.md"
